server:
  port: 8181
spring:
  application:
    name: SpringProject
  datasource:
    driver-class-name:
    url:
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  cloud:
    config:
      enabled: false
  jwt:
    secret: yourSecretKey

